local_layer: LAYERSERIES_CORENAMES -> langdale
Issue: LINCD-11129

bitbake now forbids to use LAYERSERIES_CORENAMES:
6709aedcc cookerdata: Ensure layers use LAYERSERIES_COMPAT fairly

Used LAYERSERIES_CORENAMES was because LAYERSERIES_COMPAT_local in
local/conf/layer.conf didn't get update, this has been fixed by:

afbb48a940 setup.py: update LAYERSERIES_COMPAT_local automatically

So use langdale to replace LAYERSERIES_CORENAMES to fix the error:
ERROR: Layer local is not compatible with the core layer which only supports these series: langdale (layer is compatible with ${LAYERSERIES_CORENAMES})

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>