bin/flatten_mirror.py: Skip already processed xmls
Issue: LIN1023-1193

The layer such nxp-s32g-dl is in layerindex, so the nxp-s32g-dl.xml is already
processed when process layers, this patch checks and avoids processing it
again, otherwise, there would be two nxp-s32g-dl.xml in both
WRLinux-lts-23-Core and WRLinux-lts-23-BSP-nxp-s32g which would cause setup
errors:

error: Cannot fetch WRLinux-lts-23-Core/github.com.nxp-auto-linux.ipc-shm from /url/to/WRLinux-lts-23-Core/github.com.nxp-auto-linux.ipc-shm

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>