Revert "04_wrl_buildtools.sh: update buildtools to 10.22.33.6"
Failed to build:
Exception:   File "/path/to/buildtools.buildtools-standalone-10.22.33.6/sysroots/x86_64-wrlinuxsdk-linux/usr/lib/python3.10/site-package
t/remote.py", line 700
    url = Git.polish_url(url)
IndentationError: unexpected indent

This reverts commit 62e6d03576fe196e581471d71a048ebe2e1339c1.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>